// TelemetryExport.ts
// Tier 2: Export telemetry as CSV or ROS-bag-compatible JSON

import { TelemetryHistory } from './MissionLogic';

// ── CSV Export ────────────────────────────────────────────────────────────────

const CSV_HEADERS = [
  'time_s','x_m','y_m','z_m',
  'vx_ms','vy_ms','vz_ms',
  'roll_rad','pitch_rad','yaw_rad',
  'roll_rate_rads','pitch_rate_rads','yaw_rate_rads',
  'battery_pct','energy_J',
  'servo_0','servo_1','servo_2','servo_3','servo_4','servo_5',
  'sec','spt'
];

export function exportCSV(history: TelemetryHistory[], filename = 'telemetry.csv'): void {
  const rows = [CSV_HEADERS.join(',')];

  for (const h of history) {
    const servos = h.servos ?? [0,0,0,0,0,0];
    rows.push([
      h.time.toFixed(4),
      h.x.toFixed(5), h.y.toFixed(5), h.z.toFixed(5),
      h.x_dot.toFixed(5), h.y_dot.toFixed(5), h.z_dot.toFixed(5),
      h.phi.toFixed(6), h.theta.toFixed(6), h.psi.toFixed(6),
      h.p.toFixed(6), h.q.toFixed(6), h.r.toFixed(6),
      (h.battery*100).toFixed(2), h.energyConsumed.toFixed(3),
      ...servos.map(s=>s.toFixed(5)),
      (h.sec??0).toFixed(5), (h.spt??0).toFixed(5)
    ].join(','));
  }

  const blob = new Blob([rows.join('\n')], { type: 'text/csv' });
  triggerDownload(blob, filename);
}

// ── ROS bag–compatible JSON Export ───────────────────────────────────────────
// Follows the rosbridge_suite JSON wire format so bags can be reconstructed
// with rosbag_pandas or bagpy on the researcher's machine.

export function exportROSBag(history: TelemetryHistory[], filename = 'telemetry_rosbag.json'): void {
  const messages = history.map(h => ({
    topic: '/drone/state',
    time: { secs: Math.floor(h.time), nsecs: Math.round((h.time % 1)*1e9) },
    msg: {
      header: { stamp: { secs: Math.floor(h.time), nsecs: Math.round((h.time % 1) * 1e9) }, frame_id: 'world' },
      pose: {
        position:    { x: h.x, y: h.y, z: h.z },
        orientation: eulerToQuat(h.phi, h.theta, h.psi),
      },
      twist: {
        linear:  { x: h.x_dot, y: h.y_dot, z: h.z_dot },
        angular: { x: h.p,     y: h.q,     z: h.r     },
      },
      battery:  h.battery,
      energy_j: h.energyConsumed,
      servos:   h.servos ?? [],
      sec:      h.sec  ?? 0,
      spt:      h.spt  ?? 0,
    }
  }));

  const blob = new Blob([JSON.stringify({ version: '2.0', messages }, null, 2)], {
    type: 'application/json'
  });
  triggerDownload(blob, filename);
}

// ── SB3 Training Config Export ────────────────────────────────────────────────
// Exports a ready-to-run SB3 PPO training script with the current physics config

export function exportSB3Script(
  physicsConfig: { mass: number; propDiameter: number; batteryVoltage: number; droneType: string },
  filename = 'train_ppo.py'
): void {
  const script = `#!/usr/bin/env python3
"""
Auto-generated PPO training script for Copter Studio Digital Twin.
Generated by Copter Studio Aether @ ${new Date().toISOString()}

Physics config:
  Drone type    : ${physicsConfig.droneType}
  Mass          : ${physicsConfig.mass} kg
  Prop diameter : ${physicsConfig.propDiameter} in
  Battery       : ${physicsConfig.batteryVoltage} V

Requirements:
  pip install stable-baselines3 gymnasium tensorboard
"""
import numpy as np
import gymnasium as gym
from gymnasium import spaces
from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import CheckpointCallback, EvalCallback
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize
import tensorboardX

# ── Environment ──────────────────────────────────────────────────────────────

class BicopterHoverEnv(gym.Env):
    """
    12-DOF bi-copter hover environment matching the digital twin physics.
    Observation: [x, y, z, xd, yd, zd, φ, θ, ψ, p, q, r]  (normalised)
    Action:      [col_L, cyc_lat_L, cyc_lon_L, col_R, cyc_lat_R, cyc_lon_R] ∈ [-1,1]
    """
    metadata = {'render_modes': []}

    MASS            = ${physicsConfig.mass}   # kg
    PROP_DIAM_IN    = ${physicsConfig.propDiameter}  # inches
    BATTERY_V       = ${physicsConfig.batteryVoltage}  # volts
    G               = 9.81
    DT              = 0.016       # s
    MAX_STEPS       = 1000        # ~16 s per episode

    Z_TARGET        = 1.0         # hover altitude target (m)
    CRASH_ANGLE     = 0.52        # rad — crash threshold (≈30°)
    CRASH_ALT       = 0.1         # m  — ground proximity threshold

    def __init__(self):
        super().__init__()
        self.observation_space = spaces.Box(
            low  = np.array([-5,-5, 0,-5,-5,-5,-np.pi,-np.pi,-np.pi,-5,-5,-5], dtype=np.float32),
            high = np.array([ 5, 5, 5, 5, 5, 5, np.pi, np.pi, np.pi, 5, 5, 5], dtype=np.float32),
        )
        self.action_space = spaces.Box(low=-1, high=1, shape=(6,), dtype=np.float32)
        self._state = None
        self._step  = 0

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        rng = self.np_random
        # Randomise initial conditions for robust training
        self._state = np.array([
            rng.uniform(-0.1, 0.1),   # x
            rng.uniform(-0.1, 0.1),   # y
            rng.uniform(0.8, 1.2),    # z  — start near target
            0, 0, 0,                  # velocities
            rng.uniform(-0.1, 0.1),   # phi
            rng.uniform(-0.1, 0.1),   # theta
            0,                        # psi
            0, 0, 0                   # angular rates
        ], dtype=np.float32)
        self._step = 0
        return self._state.copy(), {}

    def step(self, action):
        action = np.clip(action, -1, 1)
        s = self._state
        x,y,z,xd,yd,zd,phi,theta,psi,p,q,r = s

        # Simplified physics (matches PhysicsEngine.ts RK4 core)
        thrust_scale = 40 * (self.BATTERY_V / 22.2)**2 * (self.PROP_DIAM_IN/15)**4
        T_L = max(0, (action[0]+1)/2 * thrust_scale)
        T_R = max(0, (action[3]+1)/2 * thrust_scale)
        Fz  = T_L + T_R
        d   = 0.5
        mc  = 5.0
        L = (T_L-T_R)*d + (action[1]+action[4])*mc
        M = (action[2]+action[5])*mc
        N = (action[0]-action[3])*2

        sf  = (self.PROP_DIAM_IN/15)**2 * (self.MASS/5)
        Ixx = Iyy = 0.1*sf; Izz = 0.2*sf
        m   = self.MASS

        cp,sp = np.cos(phi),np.sin(phi)
        ct,st = np.cos(theta),np.sin(theta)
        cy,sy = np.cos(psi),np.sin(psi)

        ax = (Fz/m)*(sp*sy + cp*cy*st)
        ay = (Fz/m)*(cp*sy*st - cy*sp)
        az = (Fz/m)*(cp*ct) - self.G

        xd+=ax*self.DT; yd+=ay*self.DT; zd+=az*self.DT
        x +=xd*self.DT; y +=yd*self.DT; z +=zd*self.DT

        p_dot=(L+(Iyy-Izz)*q*r)/Ixx
        q_dot=(M+(Izz-Ixx)*p*r)/Iyy
        r_dot=(N+(Ixx-Iyy)*p*q)/Izz
        p+=p_dot*self.DT; q+=q_dot*self.DT; r+=r_dot*self.DT

        phi_dot  = p + np.tan(theta)*(q*sp+r*cp)
        theta_dot= q*cp - r*sp
        psi_dot  = (q*sp+r*cp)/max(abs(np.cos(theta)),0.001)
        phi+=phi_dot*self.DT; theta+=theta_dot*self.DT; psi+=psi_dot*self.DT

        if z < 0:
            # Spring-damper ground contact (matches PhysicsEngine.ts)
            Kn, Dn = 2000, 50
            pen = -z
            Fn = max(0, Kn * pen - Dn * zd)
            z = 0
            zd = max(0, zd + Fn * self.DT / m)
            p *= 0.8; q *= 0.8; r *= 0.9
            phi *= 0.5; theta *= 0.5  # damped attitude recovery

        self._state = np.array([x,y,z,xd,yd,zd,phi,theta,psi,p,q,r],dtype=np.float32)
        self._step += 1

        # ── Reward ──────────────────────────────────────────────────────
        alt_err   = abs(z - self.Z_TARGET)
        att_err   = abs(phi) + abs(theta)
        vel_pen   = 0.1*(xd**2+yd**2+zd**2)
        servo_pen = 0.01*np.sum(np.abs(action))

        # Gaussian altitude reward — tight peak at target
        reward  =  2.0 * np.exp(-4.0 * alt_err**2)
        # Attitude upright bonus
        reward +=  0.5 * np.exp(-2.0 * att_err)
        # Velocity damping
        reward -= vel_pen
        # Servo activity penalty
        reward -= servo_pen
        # Directional velocity penalty: only penalise downward motion when below target
        if z < self.Z_TARGET and zd < 0:
            reward -= 0.5 * abs(zd)

        # ── Termination ─────────────────────────────────────────────────
        crashed  = (z < self.CRASH_ALT and (abs(phi)>self.CRASH_ANGLE or abs(theta)>self.CRASH_ANGLE))
        timeout  = (self._step >= self.MAX_STEPS)
        truncated= timeout
        terminated=crashed

        if crashed:
            reward -= 50.0   # terminal penalty

        return self._state.copy(), float(reward), terminated, truncated, {}


# ── Training setup ────────────────────────────────────────────────────────────

def make_env():
    return BicopterHoverEnv()

if __name__ == '__main__':
    env  = DummyVecEnv([make_env])
    env  = VecNormalize(env, norm_obs=True, norm_reward=True, clip_obs=10.0)

    model = PPO(
        'MlpPolicy', env,
        learning_rate  = 3e-4,
        n_steps        = 2048,
        batch_size     = 64,
        n_epochs       = 10,
        gamma          = 0.99,
        gae_lambda     = 0.95,
        clip_range     = 0.2,
        ent_coef       = 0.005,  # Low entropy → smoother servo responses
        vf_coef        = 0.5,
        max_grad_norm  = 0.5,
        policy_kwargs  = dict(net_arch=[dict(pi=[128,128], vf=[128,128])]),
        tensorboard_log= './tb_logs/',
        verbose        = 1,
    )

    checkpoint_cb = CheckpointCallback(save_freq=50_000, save_path='./checkpoints/', name_prefix='bicop_ppo')
    eval_env      = DummyVecEnv([make_env])
    eval_cb       = EvalCallback(eval_env, best_model_save_path='./best_model/', eval_freq=25_000, n_eval_episodes=20)

    print("Training PPO agent... Monitor with: tensorboard --logdir ./tb_logs/")
    model.learn(total_timesteps=500_000, callback=[checkpoint_cb, eval_cb])
    model.save('bicop_ppo_final')

    # Export to TensorFlow.js for loading in the digital twin
    print("\\nTo export for the digital twin:")
    print("  pip install tensorflowjs")
    print("  tensorflowjs_converter --input_format=tf_saved_model bicop_ppo_final/ tfjs_model/")
    print("Then drag tfjs_model/model.json + *.bin into the Model Loader panel.")
`;

  const blob = new Blob([script], { type: 'text/plain' });
  triggerDownload(blob, filename);
}

// ── Utils ─────────────────────────────────────────────────────────────────────

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a   = document.createElement('a');
  a.href    = url;
  a.download= filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function eulerToQuat(phi: number, theta: number, psi: number) {
  const cy=Math.cos(psi/2), sy=Math.sin(psi/2);
  const cp=Math.cos(theta/2), sp=Math.sin(theta/2);
  const cr=Math.cos(phi/2), sr=Math.sin(phi/2);
  return {
    w: cr*cp*cy+sr*sp*sy,
    x: sr*cp*cy-cr*sp*sy,
    y: cr*sp*cy+sr*cp*sy,
    z: cr*cp*sy-sr*sp*cy,
  };
}
